const CloudSyncLang = {
    lang: {
        common: {
            menu_title: 'Settings Sync',
            // WARNING: `verifyConfigString` and `config_inject_header` are on-disk
            // format sentinels. `config_inject_header` is prepended to every
            // encrypted config file and stripped again on read, and
            // `verifyServerConfigIsValid()` looks for `verifyConfigString`.
            // Changing either value makes existing local and cloud configs
            // unreadable — do not edit them.
            verifyConfigString: 'This file is generated by Cloud Sync Settings Plugin',
            config_inject_header: '/*This file is generated by Cloud Sync Settings Plugin - DO NOT MODIFY THIS FILE DIRECTLY OTHERWISE PLUGIN WILL NOT WORK PROPERLY*/\n',
            errors: {
                invalidServerConfig: 'The file in the cloud is empty or does not contain valid Tabby settings.',
            },
        },
        form: {
            error: {
                required_all: 'Please fill in all the fields.',
            },
        },
        tabs: {
            general: 'General',
            security: 'Security',
            feedback: 'Feedback',
            change_logs: 'Changelog',
            check_for_update: 'Updates',
        },
        alerts: {
            debug_build: 'This is a debug build. Use a production build for day-to-day work.',
            update_available: 'Version {version} of this plugin is available. Open the Updates tab to install it.',
        },
        settings: {
            title: 'Cloud Sync Settings',
            sub_title: 'Store your Tabby configuration in the cloud and keep every device in sync.',
            service_label: 'Storage provider',
            service_hint: 'Where your Tabby configuration is stored. Pick a provider, then enter its credentials below.',
            sync_enabled_label: 'Automatic sync',
            sync_enabled_hint: 'Keep this device in sync in the background. Available once a provider has been saved.',
            show_loader_label: 'Show sync indicator',
            show_loader_hint: 'Display a small spinner in the corner of the window while a sync is running.',
            interval_label: 'Sync interval',
            interval_hint: 'How often Tabby checks the cloud for changes, in seconds. Tabby restarts when you change this.',
            encryption_title: 'Encryption',
            encryption_hint: 'Use your own secret to protect synced settings. Keep it safe: settings encrypted with it cannot be recovered if it is lost.',
            encryption_secret_label: 'Custom secret',
            encryption_secret_hint: 'Stored in your operating-system keychain and never uploaded.',
            encryption_secret_placeholder: 'Minimum 12 characters',
            encryption_confirm_label: 'Confirm secret',
            encryption_confirm_hint: 'Repeat the custom secret exactly to prevent typing mistakes.',
            encryption_confirm_placeholder: 'Enter the same secret again',
            encryption_show_secret: 'Show custom secret',
            encryption_hide_secret: 'Hide custom secret',
            encryption_show_confirmation: 'Show confirmation secret',
            encryption_hide_confirmation: 'Hide confirmation secret',
            encryption_set: 'Save secret',
            encryption_configured: 'Custom secret protection is active',
            encryption_configured_hint: 'Your synced settings now use authenticated V2 encryption with the secret stored securely in your operating-system keychain. This secret cannot be changed from this screen.',
            encryption_legacy_title: 'Your synced settings are using legacy encryption.',
            encryption_legacy_warning: 'The legacy method relies on an old shared secret and provides weaker protection. Set a unique custom secret below to upgrade to authenticated encryption and better protect your synced settings.',
            encryption_recovery_warning: 'Store this secret somewhere safe. Without it, the plugin cannot decrypt your synced settings and the encrypted data cannot be recovered.',
            encryption_mismatch: 'The two secrets do not match.',
            encryption_saved: 'Custom encryption secret saved.',
            encryption_failed: 'Could not save the custom encryption secret.',
            encryption_already_configured: 'A custom encryption secret is already active and cannot be replaced.',
            amazon: {
                connected: 'Connected to your cloud provider.',
                save_settings_failed: 'Your settings could not be saved.',
                save_settings_success: 'Your settings have been saved.',
            },
            error_connection_timeout: 'The connection timed out. Check your credentials and network, then try again.',
        },
        sync: {
            loading_config: 'Loading your saved configuration...',
            sync_confirmation: 'Settings already exist in the cloud. Which copy would you like to keep?',
            setting_valid: 'Your configuration is valid.',
            error_setting_save_file: 'Connected successfully, but the settings file could not be written to that location.',
            error_connection: 'Could not connect using these settings.',
            error_invalid_setting: 'The settings file in the cloud is not valid, so your local settings were uploaded instead.',
            error_invalid_setting_2: 'Your sync configuration is not valid. Please set it up again.',
            error_save_setting: 'Something went wrong and your settings could not be saved.',
            need_to_save_config: 'Save your configuration first.',
            sync_success: 'Your settings are now in sync.',
            sync_error: 'Could not sync your settings. Please check your configuration.',
            sync_server_failed: 'Uploading your settings to the cloud failed. Please check your cloud provider.',
            sync_enabled: 'Automatic sync is on.',
            sync_disabled: 'Automatic sync is off.',
            loader_enabled: 'The sync indicator is now visible.',
            loader_disabled: 'The sync indicator is now hidden.',
            confirm_remove_setting: 'Disconnect this cloud provider? This removes its saved configuration, sync state, and custom encryption secret from this device. Files already stored in the cloud are not deleted.',
            remove_setting_success: 'Cloud provider disconnected. Local sync settings and the custom encryption secret were cleared.',
            remove_setting_error: 'The cloud provider could not be disconnected. Please try again later.',
            remove_secret_error: 'The provider was disconnected, but the custom encryption secret could not be removed from your operating-system keychain.',
            setting_changes_saved: 'Your changes have been saved.',
            confirm_push_local: 'The cloud has no Tabby settings file. Upload the settings from this device?',
        },
        log: {
            invalid_cloud_settings: 'Invalid cloud settings syncing',
            read_cloud_settings: 'Reading cloud settings',
            error_upload_settings: 'Upload settings file from local',
            error_test_connection: 'Connection error.',
        },
        s3: {
            title: 'Enter your access key and secret',
            title_blackblaze: 'Enter your key ID and application key',
            app_id_placeholder: 'Access key ID',
            app_secret_placeholder: 'Secret access key',
            blackblaze_key_placeholder: 'Key ID',
            blackblaze_app_key_placeholder: 'Application key',
            bucket_placeholder: 'Bucket name',
            region_placeholder: 'Region (optional)',
            blackblaze_region_placeholder: 'Backblaze B2 region',
            endpoint_placeholder: 'Endpoint URL',
            location_placeholder: 'Folder path, e.g. /',
            blackblaze_region_help: 'How do I find my Backblaze B2 region code?',
        },
        ftp: {
            title: 'Enter your FTP connection details',
            host_placeholder: 'Host',
            location_placeholder: 'Folder path, e.g. /',
            username_placeholder: 'Username',
            password_placeholder: 'Password',
            port_placeholder: 'Port',
        },
        webdav: {
            title: 'Enter your WebDAV connection details',
            host_placeholder: 'Host',
            username_placeholder: 'Username or email',
            password_placeholder: 'Password',
            port_placeholder: 'Port',
            location_placeholder: 'Folder path, e.g. /',
        },
        gist: {
            title: 'Enter your Gist details',
            name: 'Description (optional)',
            id: 'Gist ID (leave empty to create a new one)',
            token: 'Access token',
            invalid_provider: 'That service provider is not supported.',
            enter_id: 'Enter a Gist ID first.',
            error_create_gist: 'Could not create a new gist. Check that your token has gist permissions.',
            help_github: 'Gists are a GitHub feature for sharing snippets and pastes. Click to learn more.',
            help_gitee: 'Gitee is a code hosting and collaboration platform. Click to learn more.',
        },
        dropbox: {
            title: 'Connect your Dropbox account',
            title_connecting: 'Waiting for Dropbox authorization...',
            callback_waiting: 'Complete authorization in your browser. Tabby will finish connecting automatically.',
            callback_listener_unavailable: 'Tabby could not start the local callback listener. Paste the callback URL below to finish connecting.',
            callback_title: 'Manual callback URL',
            callback_hint: 'If automatic return does not work, paste the URL you were redirected to below.',
            callback_invalid: 'The Dropbox callback could not be verified. Start the connection again.',
            callback_timeout: 'Dropbox authorization timed out. Try again or use the manual callback option.',
            use_manual_callback: 'Use manual callback',
            obtain_token: 'Finish connecting',
            obtaining_token: 'Connecting...',
            paste_from_clipboard: 'Paste from clipboard',
            connected: 'Connected as {email}',
            last_sync_error: 'Last sync failed: {message}',
            disconnect_account: 'Disconnect account',
            confirm_disconnect: 'Disconnect this Dropbox account? This also clears the local sync configuration and custom encryption secret. Files already stored in Dropbox are not deleted.',
            encryption_secret_title: 'Custom secret required',
            encryption_secret_required: 'Dropbox contains V2-encrypted Tabby settings. Enter the original custom secret to unlock them. The cloud file will not be overwritten.',
            encryption_secret_label: 'Custom secret used for this cloud file',
            encryption_secret_placeholder: 'Enter the original custom secret',
            encryption_secret_invalid: 'That secret could not decrypt the Dropbox settings file. Check the secret and try again.',
            encryption_secret_saved: 'Custom secret verified and saved securely in your operating-system keychain.',
            encryption_unlock: 'Unlock cloud settings',
            encryption_unlocking: 'Verifying secret...',
            missing_app_credentials: 'This plugin build does not include the Dropbox app key. Rebuild and reinstall it with DROPBOX_APP_KEY.',
            missing_callback_url: 'Paste the callback URL first.',
            connect_success: 'Connected to Dropbox.',
            clipboard_success: 'Pasted from the clipboard.',
            clipboard_error: 'Could not read the clipboard.',
        },
        builtin: {
            login_title: 'Sign in to your account',
            reset_title: 'Enter your registered email address',
            email_placeholder: 'Email',
            password_placeholder: 'Password',
            reset_notice: 'We will email you a link to reset your password. Follow the instructions in that email to finish.',
        },
        vault: {
            title: 'Master password (Vault)',
            description: 'Set a Tabby Vault password to encrypt your data. Open Vault from the left-hand menu to configure it.',
        },
        feedback: {
            title: 'Feedback and bug reports',
            description: 'This plugin is developed in the open on GitHub. Opening an issue there is the fastest way to reach the maintainer.',
            description_2: 'Include your Tabby version, the storage provider you sync with, and the steps that led to the problem.',
            open_issue_hint: 'Have a look at the existing issues first — someone may have already reported the same thing.',
        },
        changelogs: {
            title: 'Changelog',
            description: 'Everything that has changed in this plugin, newest first.',
            column_version: 'Version',
            column_date: 'Date',
            column_description: 'Changes',
        },
        updates: {
            title: 'Updates',
            current_version: 'You are running version {version}.',
            check_hint: 'Use the button below to check whether a newer version is available.',
            latest_version: 'The latest version is {version}.',
            whats_new: "What's new",
            up_to_date: 'You are running the latest version.',
            check_failed: 'Could not check for updates. Please try again later.',
            upgrade_success: 'The plugin was updated. Tabby will restart to finish.',
            rollback_title: 'Roll back to an earlier version',
            rollback_warning_backup: 'Back up your settings before rolling back. You can use the export settings feature to do that.',
            rollback_warning_risk: 'Older versions may not understand your current settings, so some configuration could be lost.',
            confirm_rollback: 'Roll back to version {version}?',
            column_version: 'Version',
            column_action: 'Action',
        },
        buttons: {
            sync_from_cloud: 'Use cloud settings',
            sync_from_local: 'Use settings from this device',
            check_update: 'Check for updates',
            yes: 'Yes',
            cancel: 'Cancel',
            no: 'No',
            ok: 'OK',
            view: 'View',
            connect: 'Connect',
            disconnect: 'Disconnect',
            open_github_issue: 'Open an issue on GitHub',
            rollback: 'Roll back',
            update_to: 'Update to {version}',
            visit_plugin_page: 'Visit the plugin page',
            login: 'Sign in',
            reset_password: 'Reset password',
            send_reset_link: 'Send reset link',
            test_connection: 'Test connection',
            processing: 'Working...',
            save_settings: 'Save settings',
            upload_settings: 'Force upload from this device',
            cloud_syncing_progress: 'Syncing with the cloud...',
            remove_saved_setting: 'Remove saved settings',
        },
    },

    /**
     * Resolve a dotted translation key (e.g. `sync.sync_success`) to its string
     * value. Returns an empty string when any segment of the path is missing or
     * the resolved value is not a string.
     *
     * Pass `replacements` to substitute `{placeholder}` tokens in the resolved
     * string, e.g. `trans('updates.current_version', { version: '1.7.0' })`.
     */
    trans: (key: string, replacements: Record<string, string | number> = {}): string => {
        let node: any = CloudSyncLang.lang
        for (const segment of key.split('.')) {
            if (node && typeof node === 'object' && typeof node[segment] !== 'undefined') {
                node = node[segment]
            } else {
                return ''
            }
        }

        if (typeof node !== 'string') {
            return ''
        }

        return Object.keys(replacements).reduce(
            (text, token) => text.split(`{${token}}`).join(String(replacements[token])),
            node as string,
        )
    },
}

export default CloudSyncLang
